### Application version ###
applicationVersion=0.1.0

### Project configs ###
projectGroup=com.sseudam

### Kapt configs ###
kapt.include.compile.classpath=false

### OpenAPI3 configs ###
openapi3Title=Sseudam API Server
openapi3Description=Sseudam API DOCS
openapi3DocsVersion=v0.1.0
openapi3JsonName=sseudam-api
openapi3IntoDirectory=src/main/resources/static/
openapi3OutDirectory=build/api-spec
openapi3LicenseName=Sseudam API Server

