services:
  backend:
    image: ${IMAGE_FULL_URL}
    container_name: ${DOCKERHUB_IMAGE_NAME}
    restart: always
    environment:
      - TZ=Asia/Seoul
      - SERVER_PORT=${SERVER_PORT:-8080}
    ports:
      - "${SERVER_PORT:-8080}:${SERVER_PORT:-8080}"
    env_file:
      - ~/.env
