services:
  backend:
    image: ${IMAGE_FULL_URL}
    container_name: ${DOCKERHUB_IMAGE_NAME}-BLUE
    restart: always
    environment:
      - TZ=Asia/Seoul
      - SERVER_PORT=8080
    network_mode: host
    env_file:
      - ~/.env
