services:
  backend:
    image: ${IMAGE_TAG}
    container_name: sseudam-backend
    restart: always
    environment:
      - TZ=Asia/Seoul
    network_mode: host
    env_file:
      - .env
  redis:
    image: "redis:alpine"
    container_name: sseudam-local-redis
    ports:
      - "6379:6379"
    environment:
      - TZ=Asia/Seoul
    network_mode: host
