services:
  sseudam-db:
    image: postgis/postgis:15-3.3
    container_name: sseudam-local-pg
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: sseudam
      POSTGRES_USER: sseudam
      POSTGRES_PASSWORD: sseudam!@
      TZ: Asia/Seoul
    command: [ "postgres", "-c", "log_statement=all" ]
    volumes:
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
