dependencies {
    compileOnly(libs.jakarta.servlet.api)
    compileOnly(libs.spring.boot.starter.test)
    api(libs.spring.restdocs.mockmvc)
    api(libs.spring.restdocs.restassured)
    api(libs.restassured.spring.mock.mvc)
    api(libs.epages.restdocs.api.spec.mock.mvc)
    api(libs.epages.restdocs.api.spec.restassured)
    api(libs.jackson.datatype.jsr310)
    api(libs.bundles.kotest)
    api(libs.kotest.runner.junit5)
    api(libs.kotest.extensions)
    api(libs.spring.boot.starter.security)
    api(libs.spring.security.test)
}
