-- ================================
-- 쓰담 서비스 초기 데이터베이스 스키마
-- ================================

-- PostGIS 확장 활성화 (공간 데이터 처리용)
CREATE EXTENSION IF NOT EXISTS postgis;

-- ================================
-- 이벤트 관련 테이블
-- ================================

-- 이벤트 레지스트리 테이블

CREATE TABLE event_publication (
    id uuid NOT NULL,
    completion_date timestamptz(6) NULL,
    event_type varchar(255) NULL,
    listener_id varchar(255) NULL,
    publication_date timestamptz(6) NULL,
    serialized_event text NULL,
    CONSTRAINT event_publication_pkey PRIMARY KEY (id)
);

-- ================================
-- 사용자 관련 테이블
-- ================================

-- 사용자 테이블
CREATE TABLE t_users (
    id BIGSERIAL PRIMARY KEY,
    user_key VARCHAR(255) NOT NULL UNIQUE,
    name VARCHAR(100),
    nickname VARCHAR(100),
    city VARCHAR(100) NOT NULL DEFAULT '',
    site VARCHAR(255) NOT NULL DEFAULT '',
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255),
    social_id VARCHAR(255),
    social_type VARCHAR(50) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    deleted_at TIMESTAMP
);

-- 사용자 디바이스 테이블
CREATE TABLE t_user_device (
    id BIGSERIAL PRIMARY KEY,
    user_id BIGINT NOT NULL,
    user_key VARCHAR(255) NOT NULL,
    fcm_token TEXT NOT NULL,
    device_id VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    deleted_at TIMESTAMP
);

-- ================================
-- 인증 관련 테이블
-- ================================

-- 인증 히스토리 테이블
CREATE TABLE t_authentication_history (
    id BIGSERIAL PRIMARY KEY,
    user_id BIGINT NOT NULL,
    user_key VARCHAR(255) NOT NULL,
    device_id VARCHAR(255),
    access_token TEXT NOT NULL,
    refresh_token TEXT NOT NULL,
    entity_status VARCHAR(50) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP
);

-- ================================
-- 쓰레기통 관련 테이블
-- ================================

-- 쓰레기통 테이블
CREATE TABLE t_trash_spot (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP(6),
    deleted_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    name VARCHAR(50),
    site VARCHAR(255),
    point GEOMETRY(POINT, 4326),
    region VARCHAR(20),
    trash_type VARCHAR(20),
    city VARCHAR(255),
    CONSTRAINT t_trash_spot_pkey PRIMARY KEY (id),
    CONSTRAINT t_trash_spot_region_check CHECK (region IN ('SEOUL', 'GYEONGGI', 'BUSAN', 'DAEGU', 'INCHEON', 'GWANGJU', 'DAEJEON', 'ULSAN', 'SEJONG', 'GANGWON', 'CHUNGBUK', 'CHUNGNAM', 'JEONBUK', 'JEONNAM', 'GYEONGBUK', 'GYEONGNAM', 'JEJU')),
    CONSTRAINT t_trash_spot_trash_type_check CHECK (trash_type IN ('GENERAL', 'RECYCLE'))
);

-- 쓰레기통 이미지 테이블
CREATE TABLE t_trash_spot_image (
    id BIGSERIAL PRIMARY KEY,
    trash_spot_id BIGINT NOT NULL,
    image_url TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    deleted_at TIMESTAMP
);

-- ================================
-- 신고/제안 관련 테이블
-- ================================

-- 쓰레기통 신고 테이블
CREATE TABLE t_spot_report (
    id BIGSERIAL PRIMARY KEY,
    spot_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    report_type VARCHAR(10) NOT NULL,
    point GEOMETRY(POINT, 4326) NOT NULL,
    city VARCHAR(100) NOT NULL,
    site VARCHAR(255) NOT NULL,
    spot_name VARCHAR(50) NOT NULL,
    region VARCHAR(15) NOT NULL,
    trash_type VARCHAR(15) NOT NULL,
    image_url TEXT NOT NULL,
    status VARCHAR(15) NOT NULL DEFAULT 'WAITING',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    deleted_at TIMESTAMP,
    CONSTRAINT t_spot_report_region_check CHECK (region IN ('SEOUL', 'GYEONGGI', 'BUSAN', 'DAEGU', 'INCHEON', 'GWANGJU', 'DAEJEON', 'ULSAN', 'SEJONG', 'GANGWON', 'CHUNGBUK', 'CHUNGNAM', 'JEONBUK', 'JEONNAM', 'GYEONGBUK', 'GYEONGNAM', 'JEJU', 'UNKNOWN')),
    CONSTRAINT t_spot_report_trash_type_check CHECK (trash_type IN ('GENERAL', 'RECYCLE')),
    CONSTRAINT t_spot_report_report_type_check CHECK (report_type IN ('POINT', 'KIND', 'PHOTO', 'NAME')),
    CONSTRAINT t_spot_report_status_check CHECK (status IN ('APPROVE', 'REJECT', 'WAITING'))
);

-- 신고 거절 테이블
CREATE TABLE t_reject_report (
    id BIGSERIAL PRIMARY KEY,
    report_id BIGINT NOT NULL,
    reason TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    deleted_at TIMESTAMP
);

-- 쓰레기통 제안 테이블
CREATE TABLE t_spot_suggestion (
    id BIGSERIAL PRIMARY KEY,
    user_id BIGINT NOT NULL,
    spot_name VARCHAR(50) NOT NULL,
    point GEOMETRY(POINT, 4326) NOT NULL,
    region VARCHAR(15) NOT NULL,
    city VARCHAR(100) NOT NULL,
    site VARCHAR(255) NOT NULL,
    trash_type VARCHAR(15) NOT NULL,
    image_url TEXT NOT NULL,
    status VARCHAR(15) NOT NULL DEFAULT 'WAITING',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    deleted_at TIMESTAMP,
    CONSTRAINT t_spot_suggestion_region_check CHECK (region IN ('SEOUL', 'GYEONGGI', 'BUSAN', 'DAEGU', 'INCHEON', 'GWANGJU', 'DAEJEON', 'ULSAN', 'SEJONG', 'GANGWON', 'CHUNGBUK', 'CHUNGNAM', 'JEONBUK', 'JEONNAM', 'GYEONGBUK', 'GYEONGNAM', 'JEJU', 'UNKNOWN')),
    CONSTRAINT t_spot_suggestion_trash_type_check CHECK (trash_type IN ('GENERAL', 'RECYCLE')),
    CONSTRAINT t_spot_suggestion_status_check CHECK (status IN ('APPROVE', 'REJECT', 'WAITING'))
);

-- ================================
-- 방문/출석 관련 테이블
-- ================================

-- 쓰레기통 방문 테이블
CREATE TABLE t_spot_visited (
    id BIGSERIAL PRIMARY KEY,
    user_id BIGINT NOT NULL,
    spot_id BIGINT NOT NULL,
    date DATE NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    deleted_at TIMESTAMP
);

-- 출석 테이블
CREATE TABLE t_attendance (
    id BIGSERIAL PRIMARY KEY,
    user_id BIGINT NOT NULL,
    date DATE NOT NULL,
    continuity INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    deleted_at TIMESTAMP
);

-- ================================
-- 펫 관련 테이블
-- ================================

-- 펫 테이블
CREATE TABLE t_pet (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    level_type VARCHAR(15) NOT NULL,
    year INTEGER NOT NULL,
    monthly VARCHAR(10) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    deleted_at TIMESTAMP
);

-- 사용자 펫 테이블
CREATE TABLE t_user_pet (
    id BIGSERIAL PRIMARY KEY,
    user_id BIGINT NOT NULL,
    pet_id BIGINT NOT NULL,
    nickname VARCHAR(100) NOT NULL,
    point BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    deleted_at TIMESTAMP
);

-- 펫 포인트 히스토리 테이블
CREATE TABLE t_pet_point_history (
    id BIGSERIAL PRIMARY KEY,
    user_pet_id BIGINT NOT NULL,
    previous_point BIGINT NOT NULL,
    additional_point BIGINT NOT NULL,
    point_action VARCHAR(50) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    deleted_at TIMESTAMP
);

-- 펫 레벨업 히스토리 테이블
CREATE TABLE t_pet_level_up_history (
    id BIGSERIAL PRIMARY KEY,
    user_id BIGINT NOT NULL,
    user_pet_id BIGINT NOT NULL,
    nickname VARCHAR(100) NOT NULL,
    year INTEGER NOT NULL,
    monthly VARCHAR(10) NOT NULL,
    level_type VARCHAR(15) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    deleted_at TIMESTAMP
);

-- ================================
-- 알림 관련 테이블
-- ================================

-- 저장된 알림 테이블
CREATE TABLE t_notification_stored (
    id BIGSERIAL PRIMARY KEY,
    notification_stored_key VARCHAR(255) NOT NULL,
    user_id BIGINT NOT NULL,
    type VARCHAR(100) NOT NULL,
    parameter_value TEXT NOT NULL,
    topic VARCHAR(255) NOT NULL,
    contents TEXT NOT NULL,
    read_status VARCHAR(10) NOT NULL DEFAULT 'UNREAD',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    deleted_at TIMESTAMP
);

-- ================================
-- 버전 관리 테이블
-- ================================

-- 앱 버전 테이블
CREATE TABLE t_app_version (
    id BIGSERIAL PRIMARY KEY,
    device_type VARCHAR(50) NOT NULL,
    current_version VARCHAR(15) NOT NULL,
    critical_version VARCHAR(15) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    deleted_at TIMESTAMP
);


-- ================================
-- 컬럼 타입 수정 스크립트
-- ================================

-- 사용자 테이블
ALTER TABLE t_users ALTER COLUMN social_type SET DATA TYPE VARCHAR(50);

-- 인증 히스토리 테이블
ALTER TABLE t_authentication_history ALTER COLUMN entity_status SET DATA TYPE VARCHAR(50);

-- 쓰레기통 테이블
ALTER TABLE t_trash_spot ALTER COLUMN name SET DATA TYPE VARCHAR(50);
ALTER TABLE t_trash_spot ALTER COLUMN region SET DATA TYPE VARCHAR(20);
ALTER TABLE t_trash_spot ALTER COLUMN trash_type SET DATA TYPE VARCHAR(20);

-- 쓰레기통 신고 테이블
ALTER TABLE t_spot_report ALTER COLUMN region SET DATA TYPE VARCHAR(15);
ALTER TABLE t_spot_report ALTER COLUMN report_type SET DATA TYPE VARCHAR(10);
ALTER TABLE t_spot_report ALTER COLUMN spot_name SET DATA TYPE VARCHAR(50);
ALTER TABLE t_spot_report ALTER COLUMN status SET DATA TYPE VARCHAR(15);
ALTER TABLE t_spot_report ALTER COLUMN trash_type SET DATA TYPE VARCHAR(15);

-- 쓰레기통 제안 테이블
ALTER TABLE t_spot_suggestion ALTER COLUMN region SET DATA TYPE VARCHAR(15);
ALTER TABLE t_spot_suggestion ALTER COLUMN spot_name SET DATA TYPE VARCHAR(50);
ALTER TABLE t_spot_suggestion ALTER COLUMN status SET DATA TYPE VARCHAR(15);
ALTER TABLE t_spot_suggestion ALTER COLUMN trash_type SET DATA TYPE VARCHAR(15);

-- 펫 테이블
ALTER TABLE t_pet ALTER COLUMN level_type SET DATA TYPE VARCHAR(15);
ALTER TABLE t_pet ALTER COLUMN monthly SET DATA TYPE VARCHAR(10);

-- 펫 레벨업 히스토리 테이블
ALTER TABLE t_pet_level_up_history ALTER COLUMN level_type SET DATA TYPE VARCHAR(15);
ALTER TABLE t_pet_level_up_history ALTER COLUMN monthly SET DATA TYPE VARCHAR(10);

-- 펫 포인트 히스토리 테이블
ALTER TABLE t_pet_point_history ALTER COLUMN point_action SET DATA TYPE VARCHAR(50);

-- 알림 테이블
ALTER TABLE t_notification_stored ALTER COLUMN read_status SET DATA TYPE VARCHAR(10);

-- 앱 버전 테이블
ALTER TABLE t_app_version ALTER COLUMN device_type SET DATA TYPE VARCHAR(50);
