openapi: 3.0.1
info:
  title: Sseudam API Server
  description: Sseudam API DOCS
  version: v0.1.0
servers:
- url: https://dev-api.sseudam.me
- url: http://localhost:8080
tags: []
paths:
  /api/v1/trash-spots:
    get:
      tags:
      - 🗑️ Trash Spot API
      summary: 쓰레기통 장소 목록 조회
      description: 쓰레기통 장소 목록 조회
      operationId: 쓰레기통 장소 목록 조회
      parameters:
      - name: region
        in: query
        description: 지역
        required: false
        schema:
          type: string
      - name: type
        in: query
        description: 쓰레기통 유형
        required: false
        schema:
          type: string
      - name: swLat
        in: query
        description: 남서쪽 위도
        required: false
        schema:
          type: string
      - name: swLng
        in: query
        description: 남서쪽 경도
        required: false
        schema:
          type: string
      - name: neLat
        in: query
        description: 북동쪽 위도
        required: false
        schema:
          type: string
      - name: neLng
        in: query
        description: 북동쪽 경도
        required: false
        schema:
          type: string
      responses:
        "200":
          description: "200"
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: "#/components/schemas/TrashSpotAllResponse"
              examples:
                쓰레기통 장소 목록 조회:
                  value: |-
                    {
                      "list" : [ {
                        "id" : 17996729856118,
                        "name" : "쑩븙ñ딘᯻桑磡慌២瓴索涜쬒ꄭ៓竈枮뀒ﺣ؛ᴕ胰ऽ㭨윤⫅맯Ɫ垏ዢ騍팔",
                        "region" : "GYEONGNAM",
                        "address" : {
                          "city" : "㔨뜬弍┧獜၇",
                          "site" : "룆孂꼈웰ↁ逸ꎇॴ훀仿꽪䋇鱄煹쪠ᇄ玈쓳䍠質켧惢च䵭政ઝ䔅됳ᛙ㉐⸪倛梶ů䊄潔໰র큖皼﬷젲적孷詇碈荍军⎇޻⺚㪍坎滕ḫ◠촓愀䴗譑隅锂㴖瀖猒쫇᜼ⴱ騤彺␆䜑腑䖏ꒅ鄍㲍毴褋ⵋ쀝"
                        },
                        "point" : {
                          "type" : "Point",
                          "coordinates" : [ 126.05, 37.24 ]
                        },
                        "trashType" : "GENERAL",
                        "updatedAt" : "2024-11-24T05:21:39.864844"
                      }, {
                        "id" : 18330,
                        "name" : "礌吒쟶쎕΅낁ㄝ◘㱏뱡쭟砎࿥",
                        "region" : "GYEONGNAM",
                        "address" : {
                          "city" : "㔨뜬弍┧獜၇",
                          "site" : "룆孂꼈웰ↁ逸ꎇॴ훀仿꽪䋇鱄煹쪠ᇄ玈쓳䍠質켧惢च䵭政ઝ䔅됳ᛙ㉐⸪倛梶ů䊄潔໰র큖皼﬷젲적孷詇碈荍军⎇޻⺚㪍坎滕ḫ◠촓愀䴗譑隅锂㴖瀖猒쫇᜼ⴱ騤彺␆䜑腑䖏ꒅ鄍㲍毴褋ⵋ쀝"
                        },
                        "point" : {
                          "type" : "Point",
                          "coordinates" : [ 126.05, 37.24 ]
                        },
                        "trashType" : "GENERAL",
                        "updatedAt" : null
                      }, {
                        "id" : -2370,
                        "name" : "໗篹⭁⡸",
                        "region" : "GYEONGNAM",
                        "address" : {
                          "city" : "㔨뜬弍┧獜၇",
                          "site" : "룆孂꼈웰ↁ逸ꎇॴ훀仿꽪䋇鱄煹쪠ᇄ玈쓳䍠質켧惢च䵭政ઝ䔅됳ᛙ㉐⸪倛梶ů䊄潔໰র큖皼﬷젲적孷詇碈荍军⎇޻⺚㪍坎滕ḫ◠촓愀䴗譑隅锂㴖瀖猒쫇᜼ⴱ騤彺␆䜑腑䖏ꒅ鄍㲍毴褋ⵋ쀝"
                        },
                        "point" : {
                          "type" : "Point",
                          "coordinates" : [ 126.05, 37.24 ]
                        },
                        "trashType" : "GENERAL",
                        "updatedAt" : "2026-06-11T09:30:12.428792"
                      }, {
                        "id" : 1161697,
                        "name" : "ྐྵ㳦",
                        "region" : "GYEONGNAM",
                        "address" : {
                          "city" : "㔨뜬弍┧獜၇",
                          "site" : "룆孂꼈웰ↁ逸ꎇॴ훀仿꽪䋇鱄煹쪠ᇄ玈쓳䍠質켧惢च䵭政ઝ䔅됳ᛙ㉐⸪倛梶ů䊄潔໰র큖皼﬷젲적孷詇碈荍军⎇޻⺚㪍坎滕ḫ◠촓愀䴗譑隅锂㴖瀖猒쫇᜼ⴱ騤彺␆䜑腑䖏ꒅ鄍㲍毴褋ⵋ쀝"
                        },
                        "point" : {
                          "type" : "Point",
                          "coordinates" : [ 126.05, 37.24 ]
                        },
                        "trashType" : "GENERAL",
                        "updatedAt" : "2025-01-07T18:07:44.005894"
                      }, {
                        "id" : -344,
                        "name" : "벪哳녻潤覺뾂",
                        "region" : "GYEONGNAM",
                        "address" : {
                          "city" : "㔨뜬弍┧獜၇",
                          "site" : "룆孂꼈웰ↁ逸ꎇॴ훀仿꽪䋇鱄煹쪠ᇄ玈쓳䍠質켧惢च䵭政ઝ䔅됳ᛙ㉐⸪倛梶ů䊄潔໰র큖皼﬷젲적孷詇碈荍军⎇޻⺚㪍坎滕ḫ◠촓愀䴗譑隅锂㴖瀖猒쫇᜼ⴱ騤彺␆䜑腑䖏ꒅ鄍㲍毴褋ⵋ쀝"
                        },
                        "point" : {
                          "type" : "Point",
                          "coordinates" : [ 126.05, 37.24 ]
                        },
                        "trashType" : "GENERAL",
                        "updatedAt" : "2026-04-19T05:44:56.210132"
                      } ]
                    }
  /api/v1/trash-spots/{spotId}:
    get:
      tags:
      - 🗑️ Trash Spot API
      summary: 쓰레기통 장소 상세 조회
      description: 쓰레기통 장소 상세 조회
      operationId: 쓰레기통 장소 상세 조회
      parameters:
      - name: spotId
        in: path
        description: 쓰레기통 장소 ID
        required: true
        schema:
          type: string
      responses:
        "200":
          description: "200"
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: "#/components/schemas/TrashSpotDetailsResponse"
              examples:
                쓰레기통 장소 상세 조회:
                  value: |-
                    {
                      "id" : 38210,
                      "suggestionerId" : null,
                      "suggestionerName" : null,
                      "name" : "뻺礬⹀┪ۯ덣䊢箙ꐒ낺蔁ⶺ雧䠳脽䄂嵞従麐蠩趂㘻ᗗ尩庩⪞챃⋣̩枳ꍴꗻ戥ṻ礄䒶㪀ಢ腔띿⋓འ聆༭⯼㘊咲",
                      "region" : "SEOUL",
                      "address" : {
                        "city" : "은평구",
                        "site" : "은평구 어디APT"
                      },
                      "point" : {
                        "type" : "Point",
                        "coordinates" : [ 126.9201620274132, 37.643421545524795 ]
                      },
                      "trashType" : "GENERAL",
                      "visitedCount" : 0,
                      "imageUrl" : "賴ᴦ䇘㙹쬉妄炉儂媁태ﲖꏁ価晶좦ﻘ᷺躠䖴鸱ꣁ붚蛣嫯",
                      "lastVisitedAt" : null,
                      "updatedAt" : "2025-01-17T13:46:30.151474"
                    }
components:
  schemas:
    TrashSpotDetailsResponse:
      title: TrashSpotDetailsResponse
      type: object
      properties:
        visitedCount:
          type: number
          description: 방문 횟수
        trashType:
          type: string
          description: 쓰레기통 유형
        address:
          type: object
          properties:
            site:
              type: string
              description: 상세 주소
            city:
              type: string
              description: 도시
          description: 주소 정보
        imageUrl:
          type: string
          description: 이미지 URL
        name:
          type: string
          description: 쓰레기통 장소명
        lastVisitedAt:
          type: string
          description: 최근 방문 시간
        suggestionerId:
          type: number
          description: 제보자 ID
        id:
          type: number
          description: 쓰레기통 장소 ID
        region:
          type: string
          description: 지역
        point:
          type: object
          properties:
            coordinates:
              type: array
              description: 좌표 배열
              items:
                oneOf:
                - type: object
                - type: boolean
                - type: string
                - type: number
            type:
              type: string
              description: 좌표 타입
          description: 좌표 정보
        suggestionerName:
          type: string
          description: 제보자 이름
        updatedAt:
          type: string
          description: 수정 시간
    TrashSpotAllResponse:
      title: TrashSpotAllResponse
      type: object
      properties:
        list:
          type: array
          description: 쓰레기통 장소 목록
          items:
            type: object
            properties:
              trashType:
                type: string
                description: 쓰레기통 유형
              address:
                type: object
                properties:
                  site:
                    type: string
                    description: 상세 주소
                  city:
                    type: string
                    description: 도시
                description: 주소 정보
              name:
                type: string
                description: 쓰레기통 장소명
              id:
                type: number
                description: 쓰레기통 장소 ID
              region:
                type: string
                description: 지역
              point:
                type: object
                properties:
                  coordinates:
                    type: array
                    description: 좌표 배열
                    items:
                      oneOf:
                      - type: object
                      - type: boolean
                      - type: string
                      - type: number
                  type:
                    type: string
                    description: 좌표 타입
                description: 좌표 정보
              updatedAt:
                type: string
                description: 수정 시간
  securitySchemes:
    Authorization:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - Authorization: []