spring:
  config:
    activate:
      on-profile: local
cloud:
  aws:
    region: ap-northeast-2
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    s3:
      bucket: ${AWS_S3_IMAGE_BUCKET}
    stack:
      auto: false
    connection-time-out: 900000
    socket-time-out: 900000
---
spring:
  config:
    activate:
      on-profile: dev
cloud:
  aws:
    region: ap-northeast-2
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    s3:
      bucket: ${AWS_S3_IMAGE_BUCKET}
    stack:
      auto: false
    connection-time-out: 900000
    socket-time-out: 900000
---
spring:
  config:
    activate:
      on-profile: prod
cloud:
  aws:
    region: ap-northeast-2
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    s3:
      bucket: ${AWS_S3_IMAGE_BUCKET}
    stack:
      auto: false
    connection-time-out: 900000
    socket-time-out: 900000
